### ISSUE TITLE
pgmodeler v0.9.2-beta is out

### ISSUE THREAD

**Issue by melissapalmer** [GrindrodBank/pgmodeler-x11#16]
**Is your feature request related to a problem? Please describe.**
pgmodeler v0.9.2-beta is out, news on their release is at: 
- https://pgmodeler.io/blog/2019/5/31/a-step-closer-to-the-092-stable-the-first-beta-of-this-series-is-ready
- https://github.com/pgmodeler/pgmodeler/blob/v0.9.2-beta/CHANGELOG.md 

**Describe the solution you'd like**
Would be great if this Docker image could be upgraded to use this latest version from pgmodeler

**Comment by mvniekerk** [comment]
Thank you for reporting
PR https://github.com/GrindrodBank/pgmodeler-x11/pull/17 to address this
