### ISSUE TITLE
pgmodeler v0.9.3-alpha is out

### ISSUE THREAD

**Issue by melissapalmer** [GrindrodBank/pgmodeler-x11#22]
**Is your feature request related to a problem? Please describe.**
pgmodeler v0.9.3-alpha is out, news on their release is at:
- https://github.com/pgmodeler/pgmodeler/blob/0.9.3-alpha/CHANGELOG.md
- https://pgmodeler.io/blog/2020/3/26/the-first-alpha-release-of-093-is-ready

**Describe the solution you'd like**
Would be great if this Docker image could be upgraded to use v0.9.3-alpha version from pgmodeler

**Comment by bikerdoodle** [comment]
I did a quick version upgrade, and rebuild. Appears to be working.

**Comment by melissapalmer** [comment]
Thanks @bikerdoodle I see your branch an all looks to be ok. 
https://github.com/GrindrodBank/pgmodeler-x11/tree/0.9.3-alpha

Please may you create a PR for this.

**Comment by melissapalmer** [comment]
This has been implemented with PR #23
